### ISSUE TITLE
Feature request: open references pane in dock

### ISSUE THREAD

**Issue by matbme** [savetheclocktower/pulsar-find-references#1]
Hi, thanks for the amazing package!

One feature I think would be interesting is the option to open the references pane inside the bottom or right "dock" (fixed pane) instead of a split.

**Comment by savetheclocktower** [comment]
You're right — that makes a lot more sense. I'll try to figure out how that would look with more of a pane-style presentation instead of copying the find-and-replace dialog.

**Comment by savetheclocktower** [comment]
So at this point, any references panel can be pinned and dragged into one of the side docks or the bottom dock. For a while I was entertaining the of making the container halfway responsive so that it would try to render more narrowly when it was in a side dock, but I didn't really come up with anything smart. For now, it looks fine.

Gonna close this as done, but re-open it if you have a more specific request that can't already be accomplished.
